# missions.yaml
missions:
  Drilling:
    - node1
    - node2
  Navigation:
    - node2
    - node3
  Sampling:
    - node1
    - node3
  Maintenance:
    - node1
    - node2
    - node3
  Teleoperation:
    - node2
  
nodes:
  node1: "ros2 run supervisor my_first_node"
  node2: "ros2 run supervisor my_second_node"
  node3: "ros2 run supervisor my_third_node"
